default: &default
  username: brojweb
  password: brojweb1
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: brojweb_dev

test: &test
  <<: *default
  database: brojweb_test

production:
  <<: *default
  database: brojweb_prod
  username: brojweb
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
